# Generated by Django 5.1.7 on 2025-03-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentticket',
            name='user',
        ),
        migrations.CreateModel(
            name='registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmocs.paymentticket')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmocs.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmocs.registereduser')),
            ],
        ),
    ]
