# Generated by Django 5.1.7 on 2025-04-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='section',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='year',
        ),
        migrations.AddField(
            model_name='registrations',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrations',
            name='utr',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
