# Generated by Django 5.1.7 on 2025-04-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0003_registrations_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=15),
        ),
    ]
