# Generated by Django 5.1.7 on 2025-04-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0004_alter_registrations_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='members',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
