# Generated by Django 5.1.7 on 2025-04-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0005_alter_registrations_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='college',
            field=models.CharField(default='MITS', max_length=100),
        ),
        migrations.AddField(
            model_name='registrations',
            name='participation_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10),
        ),
    ]
