# Generated by Django 5.1.7 on 2025-04-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0006_registrations_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='participation_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=10),
        ),
    ]
