# Generated by Django 5.1.7 on 2025-04-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0007_alter_registrations_participation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='participation_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Freefire', 'Freefire'), ('BGMI', 'BGMI'), ('Ludo', 'Ludo')], default='Offline', max_length=10),
        ),
    ]
