# Generated by Django 5.1.7 on 2025-04-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0008_alter_registrations_participation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='utr',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
