# Generated by Django 5.1.7 on 2025-04-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0008_alter_registrations_participation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='registred_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
