# Generated by Django 4.2.18 on 2025-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0009_alter_registrations_utr'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='registred_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
