# Generated by Django 5.1.7 on 2025-04-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0011_printjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='upi_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_id', models.CharField(default='hvijapuram-3@okaxis', max_length=100)),
                ('name', models.CharField(default='Harsha', max_length=50)),
            ],
        ),
    ]
