# Generated by Django 4.2.18 on 2025-04-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0012_upi_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upi_id',
        ),
    ]
