# Generated by Django 5.1.7 on 2025-04-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0013_delete_upi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='upi_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upiId', models.CharField(max_length=50)),
            ],
        ),
    ]
