# Generated by Django 5.1.7 on 2025-04-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmocs', '0014_upi_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upi_id',
            new_name='upiid',
        ),
    ]
