name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master  # Change this to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to PythonAnywhere
        run: |
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/GMOCS/webapps/gmocs.pythonanywhere.com/reload/" \
               -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}"
