name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master  # Change to your branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect & Deploy to PythonAnywhere
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ssh.pythonanywhere.com
          username: GMOCS
          password: GMOCS@2k25#  # Store your PA password as a secret
          script: |
            cd /home/GMOCS/GMOCS-2K25/gmocs2k25
            git pull origin master
            source /home/GMOCS/venv/bin/activate
            python manage.py migrate
            touch /var/www/gmocs_pythonanywhere_com_wsgi.py
