name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master  # Change to your branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect & Deploy to PythonAnywhere
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ssh.pythonanywhere.com
          username: GMOCS
          password: ${{ secrets.PA_PASSWORD }}  # Store your PA password as a secret
          script: |
            cd /home/GMOCS/GMOCS-2K25/gmocs2k25  # Navigate to Django project directory
            git pull https://HarshaVardhanRao:${{ secrets.GT_PAT }}@github.com/HarshaVardhanRao/GMOCS-2K25.git main
            source /home/GMOCS/venv/bin/activate  # Activate virtual environment
            #pip install -r requirements.txt   Install dependencies if needed
            python manage.py migrate  # Apply migrations
            # python manage.py collectstatic --noinput  # Collect static files if needed
            touch /var/www/gmocs_pythonanywhere_com_wsgi.py  # Reload Django app
